### ISSUE TITLE
suggestion: detect damage you've dealt or taken

### ISSUE THREAD

**Issue by az20101-re** [eggohito/eggolib#44]
A power which would do - detect how many damage you've dealt AND/OR taken, which could be used on both, as a condition and action.
Example - You've got damaged for 6 damage, and you deal the same amount of damage with same name onto the attacker, like thorns but 100% damage return.
I could try to explain further, if required, and yes I am that khat

**Comment by eggohito** [comment]
I've been thinking a lot and I've decided that instead of implementing something that tracks the damage dealt/taken *specifically,* I will implement something that tracks every stat in general. I'm thinking of maybe turning it something similar to a power that uses the `resource` power type, so users would be able to use it in modifiers, just like resources

What do you think?

**Comment by eggohito** [comment]
> I've been thinking a lot and I've decided that instead of implementing something that tracks the damage dealt/taken _specifically,_ I will implement something that tracks every stat in general. I'm thinking of maybe turning it something similar to a power that uses the `resource` power type, so users would be able to use it in modifiers, just like resources

This has now been implemented as of 5c0bc8a6f8a854102070ce1783d8ec853698d5c0
